### ISSUE TITLE
Should we archive this repo?

### ISSUE THREAD

**Issue by viferga** [metacall/get-started#13]
@HarshCasper and @Siddhant-K-code , should we archive this repo? Now it has been moved here: https://github.com/metacall/landing-page/blob/master/docs/getting-started.md

Here's the rendered page: https://core.metacall.io/#/docs/getting-started

Please review it and check if there's soemthing missing (i.e we should add parts of this repo to the landing page that have been omitted). Once we have it clear, we can archive this page and point all the links to the landing page.

**Comment by HarshCasper** [comment]
> @HarshCasper and @Siddhant-K-code , should we archive this repo? Now it has been moved here: https://github.com/metacall/landing-page/blob/master/docs/getting-started.md
> 
> Here's the rendered page: https://core.metacall.io/#/docs/getting-started
> 
> Please review it and check if there's soemthing missing (i.e we should add parts of this repo to the landing page that have been omitted). Once we have it clear, we can archive this page and point all the links to the landing page.

Yeah, we can do that. Or we can delete it as well since the content has been audited and refactored somewhere else.

**Comment by Siddhant-K-code** [comment]
Yeah, We Can Delete it too, and continue the future changes there only.
