### ISSUE TITLE
Metacall  ready for windows or not ?

### ISSUE THREAD

**Issue by Jassi10000-zz** [metacall/get-started#2]
Being a Windows  user , I was planning to try some hands on Metacall, 
but 
[https://raw.githubusercontent.com/metacall/install/master/install.ps1](https://raw.githubusercontent.com/metacall/install/master/install.ps1)  is returning  a 404 error ,
Is this not ready for Windows yet ???

**Comment by HarshCasper** [comment]
> Being a Windows user , I was planning to try some hands on Metacall,
> but
> https://raw.githubusercontent.com/metacall/install/master/install.ps1 is returning a 404 error ,
> Is this not ready for Windows yet ???

We don't have built binaries (yet) for Windows, you have to compile it manually.

**Comment by Jassi10000-zz** [comment]
@HarshCasper  Can you help me by giving a clear picture of how should I proceed ?

**Comment by HarshCasper** [comment]
Refer [this](https://github.com/metacall/core/blob/develop/docs/README.md#41-installation) if you are looking to install MetaCall on your local Windows.
